basePath: /
definitions:
  models.Post:
    type: object
  models.User:
    type: object
host: localhost:5000
info:
  contact: {}
  description: API simples para retornar os maiores jargões do jiu-jitsu através de
    posts objetivos.
  title: API Jiu-Jitsu Posts
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Login a user to consume API
      operationId: login-user
      parameters:
      - description: User log\in
        in: body
        name: post
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: Login user
      tags:
      - users
  /post:
    post:
      consumes:
      - application/json
      description: Create a new post in API
      operationId: create-post
      parameters:
      - description: Post create
        in: body
        name: post
        required: true
        schema:
          $ref: '#/definitions/models.Post'
      - description: Authorization header
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Post'
      security:
      - BearerAuth: []
      summary: Create post
      tags:
      - posts
  /post/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a existent post in  API by ID
      operationId: delete-post-id
      parameters:
      - description: Post ID
        in: path
        name: id
        required: true
        type: string
      - description: Authorization header
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Post'
      security:
      - BearerAuth: []
      summary: Delete post by ID
      tags:
      - posts
    put:
      consumes:
      - application/json
      description: Update existent post in  API by ID
      operationId: update-post
      parameters:
      - description: Post ID
        in: path
        name: id
        required: true
        type: string
      - description: Post to Update
        in: body
        name: post
        required: true
        schema:
          $ref: '#/definitions/models.Post'
      - description: Authorization header
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Post'
      security:
      - BearerAuth: []
      summary: Update post
      tags:
      - posts
  /posts:
    get:
      consumes:
      - application/json
      description: Get all existent posts in  API
      operationId: get-all-post
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Post'
      summary: Get all posts
      tags:
      - posts
  /posts/{id}:
    get:
      consumes:
      - application/json
      description: Get existent post in  API by ID
      operationId: get-post-id
      parameters:
      - description: Post ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Post'
      summary: Get all posts by ID
      tags:
      - posts
  /singup:
    post:
      consumes:
      - application/json
      description: Create a new user to consume API
      operationId: create-user
      parameters:
      - description: User create
        in: body
        name: post
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: Create user
      tags:
      - users
swagger: "2.0"
